// TP_Angular/Angular_2/lolmemo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ChampionService } from './champion.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

    champion : Observable<Champions[]>;

    constructor( private championService: ChampionService ) {}

    ngOnInit(){
        this.getChampions();
    }

    getChampions(): void {
        return this.championService.getChamps();
    }

    console.log(this.getChampions());
}

<div class="col-md-12 col-sm-12 col-12">
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg" alt="Ivern_0">
            <figcaption>Ivern</figcaption>
        </figure>
    </article>
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_1.jpg" alt="Ivern_1">
            <figcaption>Ivern</figcaption>
        </figure>
    </article>
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg" alt="Teemo_0">
            <figcaption>Teemo</figcaption>
        </figure>
    </article>
</div>
<div class="col-md-12 col-sm-12 col-12">
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_1.jpg" alt="Teemo_1">
            <figcaption>Teemo</figcaption>
        </figure>
    </article>
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg" alt="Taric_0">
            <figcaption>Taric</figcaption>
        </figure>
    </article>
    <article class="col-md-4 col-sm-4 col-4 thumbnail">
        <figure>
            <img class="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_1.jpg" alt="Taric_1">
            <figcaption>Taric</figcaption>
        </figure>
    </article>
</div>

// TP_React/lolmemo/src/App.js
import React, { Component } from 'react';
import './App.css';
import Data from "./data/champions.json";

class App extends Component {

    var champions = Data.map();

    render() {
        console.log(champions);
        return (
            <div className="deck">
                <div className="col-md-12 col-sm-12 col-12">
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg" alt="Ivern_0"></img>
                          <figcaption>Ivern</figcaption>
                      </figure>
                  </article>
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_1.jpg" alt="Ivern_1"></img>
                          <figcaption>Ivern</figcaption>
                      </figure>
                  </article>
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg" alt="Teemo_0"></img>
                          <figcaption>Teemo</figcaption>
                      </figure>
                  </article>
                </div>
                <div className="col-md-12 col-sm-12 col-12">
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_1.jpg" alt="Teemo_1"></img>
                          <figcaption>Teemo</figcaption>
                      </figure>
                  </article>
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg" alt="Taric_0"></img>
                          <figcaption>Taric</figcaption>
                      </figure>
                  </article>
                  <article className="col-md-4 col-sm-4 col-4 thumbnail">
                      <figure>
                          <img className="img-responsive card" src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_1.jpg" alt="Taric_1"></img>
                          <figcaption>Taric</figcaption>
                      </figure>
                  </article>
                </div>
            </div>
        );
    }
}

export default App;
